name: Patriziomoi
favicon: null
layout_spectrum: 0.6640920015051961
typography_spectrum: 0.8957752038259059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5394185427576303
  lightness: 0.9517795618157834
  saturation: 0.788193341344595
  rhythmicContrast: 0.9114767687860876
purpose: []
